package ws.siri.dtsgen.internal.emit;

import ws.siri.dtsgen.internal.JvmNames;
import ws.siri.dtsgen.internal.model.JClass;
import ws.siri.dtsgen.internal.sig.Sig;
import ws.siri.dtsgen.internal.sig.Signatures;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.TreeMap;

/**
 * Emits the single registry file that a script project includes. It carries three things:
 * package-mirroring aliases so JSDoc can name a type without importing it, the registry that
 * lets {@code Java.type("literal")} infer, and the {@code Java} object itself.
 *
 * <p>The aliases live here rather than in the per-class files on purpose. Spreading them across
 * thousands of files as ambient namespace declarations gives identical ergonomics but measured
 * 186ms editor rechecks against 49ms for this shape -- cross-file namespace merging is the cost.
 */
public final class RegistryEmitter {

    private static final String PRELUDE = """
            // Generated by DtsGenerator. Do not edit.
            //
            // Include this one file from jsconfig.json; it pulls in everything under ./full/.
            // "skipLibCheck": true is required -- Java permits overrides and inherited-member
            // conflicts that TypeScript rejects, all of them harmless inside a .d.ts.

            /** A Java array. It is a host object, not a JS array: no map, no push, fixed length. */
            interface JavaArray<T> {
              readonly length: number;
              [index: number]: T;
              [Symbol.iterator](): IterableIterator<T>;
            }

            /** The class object of a Java interface that declares no statics and no nested types. */
            interface JavaInterface {
              readonly class: unknown;
            }

            declare const Java: {
              /** Looks up a Java class by binary name, e.g. "net.minecraft.core.BlockPos$MutableBlockPos". */
              type<K extends keyof JavaTypeRegistry>(name: K): JavaTypeRegistry[K];
              /** Escape hatch for a name that is not a literal; returns an untyped value. */
              typeUnchecked(name: string): any;
              from<T>(array: JavaArray<T>): T[];
              to<T>(values: readonly T[], type?: unknown): JavaArray<T>;
              extend(...types: readonly unknown[]): any;
              super(instance: any): any;
              isJavaObject(value: unknown): boolean;
              isType(value: unknown): boolean;
              typeName(value: unknown): string | undefined;
              addToClasspath(path: string): void;
              synchronized(lock: any, body: () => void): void;
            };
            """;

    /** Directory holding the per-class modules, relative to the registry file. */
    private static final String MODULE_ROOT = "./full/";

    private final TypeUniverse universe;
    private final Set<String> includedTopLevelTypes;
    private final TypeMapper mapper;

    /**
     * @param includedTopLevelTypes binary names of the top-level classes to give a registry
     *                              entry, or null for every emitted class
     */
    public RegistryEmitter(TypeUniverse universe, Set<String> includedTopLevelTypes) {
        this.universe = universe;
        this.includedTopLevelTypes = includedTopLevelTypes;
        this.mapper = new TypeMapper(new InlineImportNaming());
    }

    /** Renders the whole registry file. */
    public String emit() {
        StringBuilder sb = new StringBuilder(PRELUDE).append('\n');
        emitAliases(sb);
        emitRegistry(sb);
        return sb.toString();
    }

    /**
     * Aliases are interfaces rather than type aliases because only an interface merges with a
     * namespace, and that merge is what makes {@code net.minecraft.core.Direction.Axis} resolve
     * as a type the way it reads in Java.
     */
    private void emitAliases(StringBuilder sb) {
        emitHiddenTypeAliases(sb);
        emitPackageNamespaces(sb);
    }

    /**
     * An interface cannot extend an {@code import(...)} type directly (TS2499 -- it accepts only
     * an identifier or qualified name), so each one is routed through a hidden top-level type
     * alias, which is an identifier.
     */
    private void emitHiddenTypeAliases(StringBuilder sb) {
        sb.append("// Indirection required by TS2499: an interface may extend an identifier but\n")
          .append("// not an import(...) type. These are an implementation detail; write the\n")
          .append("// package-qualified names below instead.\n");
        for (String internalName : includedTypes()) {
            List<Sig.Formal> formals = universe.formalsOf(universe.type(internalName));
            sb.append("type ").append(hiddenName(internalName))
              .append(mapper.renderFormals(formals, Signatures.namesOf(formals), false))
              .append(" = ").append(importRef(internalName)).append(typeArguments(formals))
              .append(";\n");
        }
        sb.append('\n');
    }

    /** One namespace per package, mirroring how the type reads in Java source. */
    private void emitPackageNamespaces(StringBuilder sb) {
        Map<String, List<String>> byPackage = new TreeMap<>();
        for (String topLevelName : universe.fileNames()) {
            if (!isIncluded(topLevelName)) continue;
            byPackage.computeIfAbsent(universe.type(topLevelName).packageName(),
                    k -> new ArrayList<>()).add(topLevelName);
        }
        for (var entry : byPackage.entrySet()) {
            sb.append("declare namespace ").append(entry.getKey()).append(" {\n");
            for (String topLevelName : entry.getValue()) {
                emitAlias(universe.type(topLevelName), sb, "  ");
            }
            sb.append("}\n");
        }
        sb.append('\n');
    }

    private void emitAlias(JClass type, StringBuilder sb, String indent) {
        String name = type.simpleName();
        List<Sig.Formal> formals = universe.formalsOf(type);

        sb.append(indent).append("interface ").append(name)
          .append(mapper.renderFormals(formals, Signatures.namesOf(formals), true))
          .append(" extends ").append(hiddenName(type.internalName()))
          .append(typeArguments(formals)).append(" {}\n");

        List<JClass> nested = universe.directNestedTypes(type);
        if (!nested.isEmpty()) {
            sb.append(indent).append("namespace ").append(name).append(" {\n");
            for (JClass child : nested) emitAlias(child, sb, indent + "  ");
            sb.append(indent).append("}\n");
        }
    }

    private void emitRegistry(StringBuilder sb) {
        sb.append("interface JavaTypeRegistry {\n");
        for (String internalName : includedTypes()) {
            sb.append("  \"").append(JvmNames.binaryName(internalName)).append("\": typeof ")
              .append(importRef(internalName)).append(";\n");
        }
        sb.append("}\n");

        if (includedTopLevelTypes != null) {
            // Pruned mode: every class name is still offered for completion, mapped to a type
            // that references nothing, so listing them costs no load.
            sb.append("\ninterface JavaTypeIndex {\n");
            for (String internalName : universe.emittedTypes()) {
                sb.append("  \"").append(JvmNames.binaryName(internalName)).append("\": 1;\n");
            }
            sb.append("}\n");
        }
    }

    /** The emitted types that get a registry entry, in emission order. */
    private List<String> includedTypes() {
        List<String> included = new ArrayList<>();
        for (String internalName : universe.emittedTypes()) {
            if (isIncluded(JvmNames.topLevel(internalName))) included.add(internalName);
        }
        return included;
    }

    /** Filtering is by owning file, so a nested type follows its top-level class. */
    private boolean isIncluded(String topLevelInternalName) {
        return includedTopLevelTypes == null
                || includedTopLevelTypes.contains(JvmNames.binaryName(topLevelInternalName));
    }

    /** A global name for one type: {@code $net_minecraft_core_Direction$Axis}. */
    private static String hiddenName(String internalName) {
        return "$" + internalName.replace('/', '_');
    }

    /** {@code <T, U>}, naming the parameters a declaration just introduced. */
    private static String typeArguments(List<Sig.Formal> formals) {
        if (formals.isEmpty()) return "";
        return "<" + String.join(", ", Signatures.namesOf(formals)) + ">";
    }

    /** {@code import("./full/net/minecraft/core/BlockPos").BlockPos.MutableBlockPos} */
    private static String importRef(String internalName) {
        String top = JvmNames.topLevel(internalName);
        String nested = JvmNames.nestedSuffix(internalName);
        return "import(\"" + MODULE_ROOT + top + "\")." + JvmNames.simpleName(top)
                + (nested == null ? "" : "." + nested);
    }

    /** Names every type by an inline {@code import(...)}, which needs no import statements. */
    private final class InlineImportNaming implements TypeMapper.Naming {

        @Override
        public String ref(String internalName) {
            return universe.isEmitted(internalName) ? importRef(internalName) : null;
        }

        @Override
        public int arity(String internalName) {
            return universe.arityOf(internalName);
        }
    }
}
